version: '3.2'
services:
  backend:
    container_name: backend
    hostname: backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./backend:/home/app