FROM python:3.10.12-alpine

ENV PYTHONUNBUFFERED=1
ENV APP_HOME=/home/app

RUN apk update
RUN apk add --no-cache gcc musl-dev postgresql-dev

RUN adduser -D app
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

COPY . $APP_HOME
RUN pip install -U pip
RUN pip install -r requirements.txt

ENTRYPOINT sh ./scripts/deploy.sh