# Generated by Django 4.2.4 on 2023-08-18 02:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Survived', models.BooleanField(default=False)),
                ('Class', models.PositiveSmallIntegerField(choices=[(1, 'First Class'), (2, 'Second Class'), (3, 'Third Class')])),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('Age', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100, 'Age must be >= 0 and <= 100')])),
                ('SibSp', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10, 'Quantity of siblings plus spouses must be >= 0 and <= 10')])),
                ('ParCh', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10, 'Quantity of parents plus children must be >= 0 and <= 10')])),
                ('Fare', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, 'Fare must be >= 0'), django.core.validators.MaxValueValidator(600.0, 'Fare must be <= 600'), django.core.validators.DecimalValidator(8, 5)])),
                ('Embarked', models.CharField(choices=[('Southampton', 'Southampton'), ('Cherbourg', 'Cherbourg'), ('Queenstown', 'Queenstown')], max_length=11)),
            ],
        ),
    ]
